### ISSUE TITLE
Support for Gulp 4?

### ISSUE THREAD

**Issue by lostPixels** [G100g/gulp-sass-partials-imported#8]
Hello, I have using your plugin for a couple of years and enjoying the benefits. However, I recently upgraded my Gulp version to 4, and the plugin doesn't seem to work any more. I was curious if there's an upgrade in the works to work with the new version.

**Comment by G100g** [comment]
Hi @lostPixels, thank you for using this plugin.

Actually I'm not using gulp anymore, and there is no plan to update this plugin to work with Gulp 4.
PR are al welcome.

But I think the effort to get the plugin works with 4 version should be low.
Let me to do a quick check.

Best

**Comment by G100g** [comment]
Hi @lostPixels,
On this branch [2.0.0](https://github.com/G100g/gulp-sass-partials-imported/tree/2.0.0) I upgraded to Gulp 4 and created a little working example.

Everything seem to works as expected.

Please give it a try and let me know.
best

**Comment by lostPixels** [comment]
Works great!
